### ISSUE TITLE
Text is dark and very hard to read

### ISSUE THREAD

**Issue by samycosa** [fabian-kho/arc_boosts#3]
![Capture d’écran 2023-03-30 à 14 14 18 (2)](https://user-images.githubusercontent.com/129394898/228833297-a1685071-50ec-4ee3-80a2-0507e35ef129.png)

**Comment by fox493** [comment]
same here

**Comment by fabian-kho** [comment]
Do you changed anything of the styles.css? The font should be white.

**Comment by fabian-kho** [comment]
Oh wait. I've added the variable --font-color. Set this to the color u want, and now you can also change only the the font-color of the sidebar in line 134 of styles.css
