### ISSUE TITLE
Can You Please Add Arc boosts link with Boost2.0 its now supported and i am doing something wrong currently please help

### ISSUE THREAD

**Issue by paranjay245** [fabian-kho/arc_boosts#7]
### Can You Please Add Arc boosts link with Boost2.0 its now supported and i am doing something wrong currently please help

**Comment by fabian-kho** [comment]
What exactly is the problem? For me everything works fine, except spotify

**Comment by paranjay245** [comment]
i was unable to install but i did through arcboosts.com thankyou : )
